/* eslint-disable */

export const articlesToAdd = [
  { title: "University finance: 'Urgent review required' over bad news", country: "United Kingdom", topics: [1] },
  { title: "North Yorkshire chippy to open restaurant in China", country: "China", topics: [2] },
  { title: "Deadly earthquake hits China's Sichuan province", country: "China", topics: [4] },
  { title: "Nike pulls Betsy Ross flag trainer 'after Kaepernick complaint'", country: "United States", topics: [6] },
  { title: "French storm: Hail batters south-east France", country: "France", topics: [4] },
  { title: "Mangalore: Inquiry ordered after India plane skids off runway", country: "India", topics: [4] },
  { title: "Glastonbury: Teenage fan Alex's rap with Dave 'too good to be true'", country: "Brazil", topics: [5] },
  { title: "A quick guide to the US-China trade war", country: "China", topics: [2] },
  { title: "Viewpoint: Why India's Chennai has run out of water", country: "India", topics: [4] },
  { title: "Wolves return to Netherlands after 140 years", country: "Netherlands", topics: [] },
  { title: "Million Welsh speakers target by 2050 backed by UK minister", country: "United Kingdom", topics: [1] },
  { title: "Brexit stockpiling warning: UK warehouses already 'full'", country: "United Kingdom", topics: [1,2] },
  { title: "Neymar rape accuser appears in Brazil TV interview", country: "Brazil", topics: [7] },
  { title: "Japan's Abe and China's Xi Jinping meet amid trade war fears", country: "China", topics: [2] },
  { title: "France prepares for 40C heatwave", country: "France", topics: [] },
  { title: "Germany's Angela Merkel seen shaking again in Berlin", country: "Germany", topics: [1] },
  { title: "G20 summit: Trump and Xi agree to restart US-China trade talks", country: "China", topics: [2] },
  { title: "Spirited Away: Japanese anime trounces Toy Story 4 at China box office", country: "China", topics: [5] },
  { title: "Is there a crisis on the US-Mexico border?", country: "Mexico", topics: [1] },
  { title: "Paris attacks: Bosnian suspect arrested in Germany", country: "Germany", topics: [4] },
  { title: "Tory tensions over keeping the UK intact", country: "United Kingdom", topics: [1] },
  { title: "G20 summit: Trump halts new China tariffs as Huawei policy changes", country: "China", topics: [2] },
  { title: "Deportations after deal: The new reality for migrants in Mexico", country: "Mexico", topics: [1] },
  { title: "Germany crash: Two Eurofighter jets in fatal collision", country: "Germany", topics: [4] },
  { title: "May: Russia must stop 'destabilising' activities", country: "Russia", topics: [4] },
  { title: "Pakistan’s ex-President Zardari arrested on corruption charges", country: "Pakistan", topics: [7] },
  { title: "Scotch whisky targeted by new US tariffs", country: "United States", topics: [2] },
  { title: "Netherlands 'hosts most child sex abuse images'", country: "Netherlands", topics: [] },
  { title: "Lee Boswell: Man drowned in Mexico 'after head injury'", country: "Mexico", topics: [] },
  { title: "India arrests after mob attacks female forest officer", country: "India", topics: [] },
  { title: "China suspends Canadian beef, pork imports as tensions rise", country: "China", topics: [] },
  { title: "Hong Kong protests: China says protesters 'trample rule of law'", country: "China", topics: [] },
  { title: "What's happening in the news this week?", country: "Netherlands", topics: [] },
  { title: "France heatwave: Paris region closes schools", country: "France", topics: [] },
  { title: "Prince William and Kate to visit Pakistan in autumn", country: "Pakistan", topics: [] },
  { title: "US ambassador Edward Crawford meets Irish president", country: "United States", topics: [] },
  { title: "What happens if Mexico doesn't stem migrant flow?", country: "Mexico", topics: [] },
  { title: "Germany's Angela Merkel seen shaking for second time", country: "Germany", topics: [] },
  { title: "EU Commission boss: Who will replace Jean-Claude Juncker?", country: "Netherlands", topics: [] },
  { title: "Wolfenstein: Youngblood - Nazi images shown in first for Germany", country: "Germany", topics: [] },
  { title: "Avalanche traps climbers in northern Pakistan", country: "Pakistan", topics: [] },
  { title: "Mexico violence: Journalist Norma Sarabia shot dead", country: "Mexico", topics: [] },
  { title: "Welsh FM scaremongering over the union post-Brexit, says Cairns", country: "United Kingdom", topics: [] },
  { title: "Joyce Burgess death: Burglar Johnny Brazil admits manslaughter", country: "Brazil", topics: [] },
  { title: "Brexit: First ministers call for next PM to reject no deal", country: "United Kingdom", topics: [] },
  { title: "FIFA Women's World Cup 2019: Lionesses fans plan for semi-final", country: "Netherlands", topics: [] },
  { title: "Russia holiday camp deaths: Officials to return to court", country: "Russia", topics: [] },
  { title: "Germany's Angela Merkel 'fine' after seen shaking in heatwave", country: "Germany", topics: [] },
  { title: "India arrests after women's heads shaved for resisting rape", country: "India", topics: [] },
  { title: "Assam NRC: Are India’s ‘unwanted people’ being driven to suicide?", country: "India", topics: [] },
  { title: "Pakistan avalanche: Six trapped climbers rescued from mountain", country: "Pakistan", topics: [] },
  { title: "France heatwave threatens 40C June day", country: "France", topics: [] },
  { title: "Mexico's top Caribbean beaches hit by seaweed infestation", country: "Mexico", topics: [] },
  { title: "France's raw recruits sign up for return of national service", country: "France", topics: [] },
  { title: "Russia's Vladimir Putin: Liberalism 'outlived its purpose'", country: "Russia", topics: [] },
  { title: "Can Mexico stop the migrant flow?", country: "Mexico", topics: [] },
  { title: "Donald Trump hits out at 'unacceptable' India tariffs", country: "India", topics: [] },
  { title: "European heatwave: France hits record temperature of 45.9C", country: "France", topics: [] },
  { title: "Ellen White's 'goggles' celebration marked in Aylesbury mural", country: "United States", topics: [] },
  { title: "G20 summit: Russia's Putin grabs headlines in Osaka", country: "Russia", topics: [] },
  { title: "Plumes of smoke as fighter jets crash over Germany", country: "Germany", topics: [] },
  { title: "Russia denies role in Israeli airport GPS jamming", country: "Russia", topics: [] },
  { title: "Waste giant Biffa guilty of sending nappies to China", country: "China", topics: [] },
  { title: "China loses ground in top supercomputer list", country: "China", topics: [] },
  { title: "India cricket team's orange kit plans sparks political row", country: "India", topics: [] },
  { title: "Pakistan ad 'mocking' India pilot ups ante ahead of World Cup clash", country: "Pakistan", topics: [] },
  { title: "Climate protesters storm Garzweiler coalmine in Germany", country: "Germany", topics: [] },
  { title: "Pakistan MQM founder Altaf Hussain arrested in UK", country: "Pakistan", topics: [] },
  { title: "Lula: Brazil court rejects request to free ex-president pending appeal", country: "Brazil", topics: [] },
  { title: "Inside China’s 'thought transformation' camps", country: "China", topics: [] },
  { title: "Elton John awarded France's highest civilian award Legion d'Honneur", country: "France", topics: [] },
  { title: "Hail batters south-east France", country: "France", topics: [] },
  { title: "England v India at the Cricket World Cup: A clash of cultures", country: "India", topics: [] },
  { title: "Germany's Ursula von der Leyen nominated to lead EU Commission", country: "Germany", topics: [] },
  { title: "Russia: Fire kills 14 sailors aboard navy research submersible", country: "Russia", topics: [] },
  { title: "Mumbai: Deadly floods bring India's financial capital to standstill", country: "India", topics: [] },
  { title: "Mexico hail: Ice 1.5m thick carpets Guadalajara", country: "Mexico", topics: [] },
  { title: "Andre Marshall: Man held in Pakistan over 2015 killing", country: "Pakistan", topics: [] },
  { title: "Cricket World Cup: India v Pakistan in Manchester prompts huge crowds", country: "Pakistan", topics: [] },
  { title: "Fishing for crabs in Brazil's mangrove forests", country: "Brazil", topics: [] },
  { title: "Russia Siberia: At least 18 people killed by floods", country: "Russia", topics: [] },
  { title: "United States dilutes UN rape-in-war resolution", country: "United States", topics: [] },
  { title: "Liam Fox: No-deal Brexit 'threatens' UK break up", country: "United Kingdom", topics: [] },
  { title: "Pakistan: How one girl overcame the armed men who blocked her school", country: "Pakistan", topics: [] },
  { title: "Brexit: Hammond vows to oppose '£90bn no-deal hit'", country: "United Kingdom", topics: [] },
  { title: "France 40C heatwave could break June records", country: "France", topics: [] },
  { title: "Inside Pakistan's first retirement home for third-gender people", country: "Pakistan", topics: [] },
  { title: "Brazil justice minister Sergio Moro denies conspiring against Lula", country: "Brazil", topics: [] },
  { title: "Boris Johnson and Jeremy Hunt pledge to safeguard union", country: "United Kingdom", topics: [] },
  { title: "How China is trying to stop its deserts spreading", country: "China", topics: [] },
  { title: "Used car batteries may power football stadium lights", country: "Netherlands", topics: [] },
  { title: "Jair Bolsonaro: Man who stabbed Brazil's leader acquitted", country: "Brazil", topics: [] },
  { title: "G20 summit: Trump confirms no new China trade tariffs", country: "China", topics: [] },
  { title: "Hells Angels bikers banned by Netherlands court", country: "Netherlands", topics: [] },
  { title: "Asif Ali Zardari: Former Pakistan President Zardari arrested", country: "Pakistan", topics: [] },
  { title: "China's investment in Africa: Everything you need to know", country: "China", topics: [] },
  { title: "Russia camp deaths: Officials to return to court", country: "Russia", topics: [] },
  { title: "Mexico auctions drug lords' properties to fund poor communities", country: "Mexico", topics: [] },
  { title: "Calls for more cycling resources in the Republic of Ireland", country: "Netherlands", topics: [] },
  { title: "'World's best restaurant' is France's Mirazur", country: "France", topics: [] },
  { title: "Frida, Mexico's famous rescue dog, retires", country: "Mexico", topics: [] },
  { title: "Russia says Georgia isn't safe. Russians in Georgia say otherwise", country: "Russia", topics: [] },
  { title: "Is the United States heading for war with Iran?", country: "United States", topics: [] },
  { title: "Eurovision 2019: Netherlands wins song contest", country: "Netherlands", topics: [] },
  { title: "Brazil hit by general strike against pension reform", country: "Brazil", topics: [] },
  { title: "Germany to return Nazi-stolen painting Vase of Flowers to Italy", country: "Germany", topics: [] },
  { title: "FlyBe: Racism claims denied by airline following viral video", country: "Netherlands", topics: [] },
];
