export const articlesToAdd = [
  { title: 'New 1', country: 'USA' },
  { title: 'New 2', country: 'UK' },
  { title: 'New 3', country: 'UK' },
  { title: 'New 4', country: 'UK' },
  { title: 'New 5', country: 'Netherlands' },
  { title: 'New 6', country: 'UK' },
  { title: 'New 7', country: 'Netherlands' },
  { title: 'New 8', country: 'Netherlands' },
  { title: 'New 9', country: 'USA' },
  { title: 'New 10', country: 'USA' },
  { title: 'New 11', country: 'Netherlands' },
  { title: 'New 12', country: 'UK' },
  { title: 'New 13', country: 'USA' },
  { title: 'New 14', country: 'USA' },
  { title: 'New 15', country: 'Netherlands' },
  { title: 'New 16', country: 'USA' },
  { title: 'New 17', country: 'USA' },
  { title: 'New 18', country: 'USA' },
  { title: 'New 19', country: 'UK' },
];
