export const articlesToAdd = [
  { title: 'New 1', country: 'United States', topics: [2, 4, 3] },
  { title: 'New 10', country: 'United States', topics: [2] },
  { title: 'New 3', country: 'Germany', topics: [2, 5, 3] },
  { title: 'New 4', country: 'United Kingdom', topics: [2, 3] },
  { title: 'New 5', country: 'France', topics: [3] },
  { title: 'New 6', country: 'Netherlands', topics: [2, 5, 3] },
  { title: 'New 7', country: 'France', topics: [1, 5, 2] },
  { title: 'New 8', country: 'Germany', topics: [3] },
  { title: 'New 9', country: 'United States', topics: [1, 4, 3] },
  { title: 'New 11', country: 'Netherlands', topics: [1, 4, 3] },
  { title: 'New 12', country: 'Germany', topics: [2, 5, 3] },
  { title: 'New 13', country: 'United States', topics: [1, 3] },
  { title: 'New 14', country: 'United States', topics: [1, 2, 3] },
  { title: 'New 15', country: 'France', topics: [1, 5, 3] },
  { title: 'New 16', country: 'United States', topics: [2, 4, 1] },
  { title: 'New 17', country: 'United States', topics: [2, 3] },
  { title: 'New 18', country: 'Germany', topics: [1, 5, 4] },
  { title: 'New 19', country: 'United Kingdom', topics: [1, 2, 3] },
  { title: 'New 20', country: 'France', topics: [1, 5, 3] },
  { title: 'New 21', country: 'Netherlands', topics: [1, 4, 3] },
  { title: 'New 22', country: 'United Kingdom', topics: [2, 5, 3] },
  { title: 'New 23', country: 'United States', topics: [1, 3] },
  { title: 'New 24', country: 'United States', topics: [1, 2, 3] },
  { title: 'New 25', country: 'Netherlands', topics: [1, 5, 3] },
  { title: 'New 26', country: 'United States', topics: [2, 4, 1] },
  { title: 'New 27', country: 'United States', topics: [2, 3] },
  { title: 'New 28', country: 'United States', topics: [1, 5, 4] },
  { title: 'New 29', country: 'United Kingdom', topics: [1, 2, 3] },
];
