/* eslint-disable */
export const datasetInit = {
  'United States': [
    { title: 'Article 1', topics: [1, 5, 3] },
    { title: 'Article 2', topics: [1] },
    { title: 'Article 3', topics: [4, 3] },
    { title: 'Article 4', topics: [4, 3] },
    { title: 'Article 5', topics: [4, 3] },
  ],
  'United Kingdom': [
    { title: "Theresa May has struck a deal with Brussels", topics: [] },
    { title: "The agreement may give UK firms continued access to the European Union's finance market after Brexit.", topics: [] },
    { title: "Dominic Raab warns that obstacles remain but insists the end is now firmly in sight", topics: [] },
    { title: "The Prime Minister announced that austerity is over", topics: [] },
    { title: "Serious and organised crime in the UK is costing the economy £37bn a year", topics: [] },
    { title: "Medicinal cannabis products can now be legally prescribed to some patients across the UK", topics: [] },
    { title: "Merseyside cops are hunting a man who pulled a knife on a mum and her kids", topics: [] },
    { title: "Sara Thornton says treating misogyny as a hate crime could not be a priority for a service that is over-stretched", topics: [] },
    { title: "Boris Johnson accepted a £14,000 trip to Saudi Arabia", topics: [] },
    { title: "Preserving the EU's cohesion outweighs the risks from the UK crashing out with no deal", topics: [] },
    { title: "Figures from Waitrose suggest animal welfare, environmental and health concerns driving sea change in UK diet.", topics: [] },
    { title: "The editor of Waitrose Food magazine, William Sitwell, is standing down", topics: [] },
    { title: "More than half of Brits are being caught out by sneaky car and home insurance tactics", topics: [] },
    { title: "The City regulator warns customers face significant harm from the prices charged by some firms", topics: [] },
    { title: "Channel Four will move its headquarters to Leeds", topics: [] },
    { title: "The Apprentice's Rick Monk has slammed co-star Kurran Pooni for being 'a dead weight'", topics: [] },
    { title: "The Duchess of Cambridge has paid a surprise visit to London's Imperial War Museum", topics: [] },
    { title: "Robbie Williams won't be on the X Factor on Sunday", topics: [] },
    { title: "The London trio all moved into the quarter-finals with victories on Wednesday night.", topics: [] },
    { title: "The former Chelsea midfielder returns to Stamford Bridge", topics: [] },
  ],
  Netherlands: [
    { title: 'Article 12', topics: [1] },
    { title: 'Article 13', topics: [5] },
    { title: 'Article 14', topics: [1, 3] },
    { title: 'Article 15', topics: [4] },
    { title: 'Article 16', topics: [2] },
    { title: 'Article 17', topics: [2] },
  ],
  Germany: [
    { title: 'Article 18', topics: [1] },
    { title: 'Article 19', topics: [5] },
    { title: 'Article 20', topics: [1, 3] },
    { title: 'Article 21', topics: [4] },
    { title: 'Article 22', topics: [2] },
    { title: 'Article 23', topics: [2] },
  ],
  France: [
    { title: 'Article 24', topics: [1] },
    { title: 'Article 25', topics: [5] },
    { title: 'Article 26', topics: [1, 3] },
    { title: 'Article 27', topics: [4] },
    { title: 'Article 28', topics: [2] },
    { title: 'Article 29', topics: [2] },
  ],
};
