/* eslint-disable */
export const datasetInit = {
  'United States': [
    // { title: "EU-Swiss share trading row: What does it mean?", topics: [1] },
    // { title: "US-Iran tensions: How social media reacted", topics: [1] },
    // { title: "Marianne Williamson: Presidential hopeful winning Reddit votes", topics: [1] },
    // { title: "'My struggle transcends race'", topics: [1] },
    // { title: "Sudan crisis: New sense of hope for young revolutionaries", topics: [1] },
    // { title: "New York Pride: Bumper crowds attend LGBT march", topics: [1] },
    // { title: "First autogyro round-the-world trip completed by Larne pilot", topics: [1] },
    // { title: "Venezuela crisis: US announces sanctions against Maduro's son", topics: [1] },
    // { title: "Canada resettled more refugees than any other country in 2018", topics: [1] },
    // { title: "Cornwall man charged with UK and US bomb threat hoaxes", topics: [1] },
    // { title: "Iran's nuclear deal is on life support. Can it be saved?", topics: [1] },
    // { title: "Stagecoach pulls out of United States", topics: [1] },
    // { title: "Longhorsley vicar Peter McConnell guilty of drunken plane grope", topics: [1] },
    // { title: "Democratic debate: Joe Biden criticised for race record", topics: [1] },
    // { title: "Narnia creator CS Lewis's letters to children go on sale", topics: [1] },
    // { title: "Caravan migrants reach United States border", topics: [1] },
    // { title: "Prom costs: How families pay for the big night", topics: [1] },
    // { title: "Wayfair staff to walk out over sales to detention centres", topics: [1] },
    // { title: "Mexican cops told to slim down for National Guard", topics: [1] },
  ],
  // 'United Kingdom': [
  //   { title: "Japan urges UK to avoid no-deal Brexit", topics: [1] },
  //   { title: "United Kingdom profile - Media", topics: [1] },
  //   { title: "Nazanin Zaghari-Ratcliffe ends Iran hunger strike after 15 days", topics: [1] },
  //   { title: "New Edinburgh Castle governor is Robert the Bruce descendant", topics: [1] },
  //   { title: "Willie Frazer, founder of Families Acting for Innocent Relatives, dies", topics: [1] },
  //   { title: "Queen's former Malta home Villa Guardamangia on sale", topics: [1] },
  //   { title: "Brexit: Survival of UK in doubt, Gordon Brown warns", topics: [1] },
  //   { title: "Conservative leadership: Ruth Davidson now backing Jeremy Hunt", topics: [1] },
  //   { title: "What is the G20 summit, and what do world leaders talk about?", topics: [1] },
  //   { title: "Jeremy Hunt would not allow UK break-up", topics: [1] },
  //   { title: "Brexit: Business group to consider backstop alternatives", topics: [1] },
  //   { title: "United Kingdom profile - Timeline", topics: [1] },
  //   { title: "Latest from the Commons", topics: [1] },
  //   { title: "Service marks 100 years since Scapa Flow navy scuttling", topics: [1] },
  //   { title: "Welsh migration rules to be considered by expert panel", topics: [1] },
  //   { title: "NHS Wales: Court action if trade deals affect service?", topics: [1] },
  //   { title: "Bank of England cuts UK growth outlook as rates held", topics: [1] },
  //   { title: "Tory leadership: Boris Johnson and Jeremy Hunt on Scotland", topics: [1] },
  //   { title: "Awkward squad or team player? Indy Scotland in Europe", topics: [1] },
  // ],
  // Netherlands: [
  //   { title: "'Victim fashion': Netherlands rail defends controversial campaign amid backlash", topics: [1] },
  //   { title: "Holocaust: Dutch rail firm NS confirms compensation", topics: [1] },
  //   { title: "Punk band Crows has 'unique' guitar stolen from van", topics: [1] },
  //   { title: "Italy migrant boat: Rescue captain accused of trying to sink police boat", topics: [1] },
  //   { title: "Leicester father expects 'no justice' over MH17 crash", topics: [1] },
  //   { title: "Italy migrants: Rescue ship reaches Lampedusa despite warnings", topics: [1] },
  //   { title: "Italy migrants: Pressure builds over Lampedusa rescue ship", topics: [1] },
  //   { title: "Endgame nears for British Steel bids", topics: [1] },
  //   { title: "French police under fire over man missing at Nantes party", topics: [1] },
  //   { title: "The death of a Tunisian poet and the hidden story of Arab mental health", topics: [1] },
  //   { title: "Van driver sentenced over 840 illegal vodka bottles", topics: [1] },
  //   { title: "Cambodia translator jailed over 'fake news' sex trade documentary", topics: [1] },
  //   { title: "New Year's Eve beach bonfire sparks 'firenados' in the Netherlands", topics: [1] },
  //   { title: "First euthanasia prosecution launched in the Netherlands", topics: [1] },
  //   { title: "Jogger in Netherlands finds lion cub", topics: [1] },
  //   { title: "Strong sales of malt whiskies lift sales for Edrington", topics: [1] },
  //   { title: "Archaeologists unearth Roman road in Netherlands", topics: [1] },
  //   { title: "Dutch emergency line hit by KPN telecoms outage", topics: [1] },
  // ],
  // Germany: [
  //   { title: "Ursula von der Leyen: Merkel ally nominated for EU top job", topics: [1] },
  //   { title: "Germany's far-right AfD party fails to win first mayor", topics: [1] },
  //   { title: "Economic clouds gather over Germany", topics: [1] },
  //   { title: "Angela Merkel: Germany's shrewd political survivor", topics: [1] },
  //   { title: "Germany's Merkel vows to carry on despite coalition setback", topics: [1] },
  //   { title: "Why is there a Little Germany in Bradford?", topics: [1] },
  //   { title: "Being black in Nazi Germany", topics: [1] },
  //   { title: "EU Commission: France and Germany differ on Brussels' top job", topics: [1] },
  //   { title: "Germany sex trafficking: Thai forced prostitution trial begins", topics: [1] },
  //   { title: "Colonia Dignidad: Germany to compensate Chile commune victims", topics: [1] },
  //   { title: "Germany labels Israel boycott movement BDS anti-Semitic", topics: [1] },
  //   { title: "Germany to return Portuguese Stone Cross to Namibia", topics: [1] },
  //   { title: "Secret RAF WWII maps unveiled in Buckinghamshire", topics: [1] },
  //   { title: "MEPs get back to work: Four things to look for", topics: [1] },
  //   { title: "Meet the European Parliament's youngest ever MEP", topics: [1] },
  //   { title: "Princess Haya: Dubai ruler's wife in UK 'in fear of her life'", topics: [1] },
  //   { title: "Group B Strep: NI parties call for mothers-to-be screening", topics: [1] },
  //   { title: "Man killed by crossbow in Germany led 'medieval cult'", topics: [1] },
  //   { title: "Iran nuclear deal: Enriched uranium limit breached, IAEA confirms", topics: [1] },
  //   { title: "Colonia Dignidad: Germany drops probe into sect doctor", topics: [1] },
  // ],
  // France: [
  //   { title: "George Osborne and wife Frances announce divorce", topics: [1] },
  //   { title: "Climate change: Heatwave made 'at least' five times more likely by warming", topics: [1] },
  //   { title: "D-Day anniversary events in northern France", topics: [1] },
  //   { title: "Prehistoric stone engraved with horses found in France", topics: [1] },
  //   { title: "France jails imam over Channel migrant crossings", topics: [1] },
  //   { title: "D-Day veteran, 95, parachutes into France to mark anniversary", topics: [1] },
  //   { title: "Tan France: Queer Eye star 'bleached skin as a child'", topics: [1] },
  //   { title: "British soldier L/Cpl Darren Jones 'drowns in France'", topics: [1] },
  //   { title: "GE to cut over 1,000 jobs in France", topics: [1] },
  //   { title: "France's MeToo creator on trial for defaming man she accused", topics: [1] },
  //   { title: "France Lyon: Police arrest suspects in parcel bomb attack", topics: [1] },
  //   { title: "France's Macron urges Brexit clarity after May resignation", topics: [1] },
  //   { title: "France Lyon: Police appeal after parcel bomb attack hurts 13", topics: [1] },
  //   { title: "Historic sailing race The Transat ditches Plymouth for France", topics: [1] },
  //   { title: "In pictures: Europe roasting again as heatwave continues", topics: [1] },
  //   { title: "Woman of 102 suspected of care home murder in France", topics: [1] },
  // ],
  // 'Russia': [
  //   { title: "Ukraine fury as Russia gets back Council of Europe voting rights", topics: [1] },
  //   { title: "Facebook: Nick Clegg says 'no evidence' Russia influenced Brexit", topics: [1] },
  //   { title: "Russia suspends Georgia flights after violent clashes", topics: [1] },
  //   { title: "Russia and Putin: Is president's popularity in decline?", topics: [1] },
  //   { title: "MH17 crash: Putin says Russia 'absolutely disagrees' with evidence", topics: [1] },
  //   { title: "Russia to release whales from 'jail' in far east after outcry", topics: [1] },
  //   { title: "US and Russia clash over power grid 'hack attacks'", topics: [1] },
  //   { title: "UK's special forces set for new Russia mission", topics: [1] },
  //   { title: "Ukraine's landmines endangering children", topics: [1] },
  //   { title: "Russia Golunov case: Putin sacks top Moscow police officials", topics: [1] },
  //   { title: "What Turkey's S-400 missile deal with Russia means for Nato", topics: [1] },
  //   { title: "Russia fines 'whale jail' company White Whale", topics: [1] },
  //   { title: "The anti-corruption case that touched a Russian nerve", topics: [1] },
  //   { title: "'Metal thieves' steal rail bridge in Russia", topics: [1] },
  //   { title: "China's Xi praises 'best friend' Putin during Russia visit", topics: [1] },
  //   { title: "Russia and US warships almost collide in East China Sea", topics: [1] },
  //   { title: "Russia to make its own show about Chernobyl that implicates the US", topics: [1] },
  //   { title: "Elton John 'rejects' Russia censorship of Rocketman gay scenes", topics: [1] },
  //   { title: "Russia ordered to release Ukraine sailors", topics: [1] },
  //   { title: "Is lesbian kiss in Crimean play 'gay propaganda'?", topics: [1] },
  //   { title: "Russia 'probably' conducting banned nuclear tests, US official says", topics: [1] },
  // ],
  // 'China': [
  //   { title: "Trump offers to help Canada in rift with China", topics: [1] },
  //   { title: "Searching for truth in China's Uighur 're-education' camps", topics: [1] },
  //   { title: "Faith in ruins: China's vanishing beards and mosques", topics: [1] },
  //   { title: "Xi in North Korea: Kim hails 'invincible' ties with China", topics: [1] },
  //   { title: "Apple warns Trump that more China tariffs will help rivals", topics: [1] },
  //   { title: "Ex-Interpol chief pleads guilty to corruption, China says", topics: [1] },
  //   { title: "Trump offers 'anything' to help Canada in rift with China", topics: [1] },
  //   { title: "China’s history of extraordinary rendition", topics: [1] },
  //   { title: "China rains: Thousands stranded in southern China", topics: [1] },
  //   { title: "Xi Jinping visits N Korea to boost China's ties with Kim", topics: [1] },
  //   { title: "Bangladesh and China power plant workers in deadly mass brawl", topics: [1] },
  //   { title: "US-China trade war: Officials to resume talks before G20", topics: [1] },
  //   { title: "UK to launch 'groundbreaking' China stock market link", topics: [1] },
  //   { title: "China opens beef market to offer export hope to Wales", topics: [1] },
  //   { title: "Why are there protests in Hong Kong? All the context you need", topics: [1] },
  // ],
  // 'India': [
  //   { title: "India elephants' 1,900-mile train journey suspended after protest", topics: [1] },
  //   { title: "Did the world's tallest statue bring development to India?", topics: [1] },
  //   { title: "Bihar encephalitis deaths reveal cracks in India healthcare", topics: [1] },
  //   { title: "India tent collapse: Desperate search for survivors", topics: [1] },
  //   { title: "Jharkhand: Arrests over lynching of India Muslim man", topics: [1] },
  //   { title: "What is India's caste system?", topics: [1] },
  //   { title: "Fears for elephants facing 1,900 mile train journey in India", topics: [1] },
  //   { title: "India encephalitis death toll rises to 103", topics: [1] },
  //   { title: "Viewpoint: How the British reshaped India's caste system", topics: [1] },
  //   { title: "India to Wales: The trafficked children rescued from the circus", topics: [1] },
  //   { title: "Kullu bus crash: More than 40 die in India gorge plunge", topics: [1] },
  //   { title: "Chennai water: How India's sixth biggest city is coping with shortages", topics: [1] },
  //   { title: "Sanjiv Bhatt: India riots whistleblower gets life in jail for murder", topics: [1] },
  //   { title: "India magician disappears in river after Houdini trick", topics: [1] },
  //   { title: "Mumbai: Heaviest rain in decade triggers chaos", topics: [1] },
  //   { title: "India announces retaliatory trade tariffs against the US", topics: [1] },
  //   { title: "Is India exaggerating its economic growth?", topics: [1] },
  //   { title: "Seven die while cleaning hotel sewer in India's Gujarat", topics: [1] },
  //   { title: "Cyclone Vayu: India cyclone changes course overnight", topics: [1] },
  //   { title: "Chandrayaan-2: India unveils spacecraft for second Moon mission", topics: [1] },
  // ],
  // 'Mexico': [
  //   { title: "Trump reveals Mexico migrant plan by waving document around", topics: [1] },
  //   { title: "Mexico says sale of presidential plane will curb illegal migration", topics: [1] },
  //   { title: "Mexico to deploy forces on Guatemala border", topics: [1] },
  //   { title: "Mexico 'has 45 days to curb migrant flow to US'", topics: [1] },
  //   { title: "US Border Patrol investigate ‘disturbing’ secret Facebook group", topics: [1] },
  //   { title: "Republicans clash with Trump over Mexico tariffs", topics: [1] },
  //   { title: "Mexico City drops gender-specific school uniforms", topics: [1] },
  //   { title: "US-Mexico talks: Agreement to avoid tariffs reached, says Trump", topics: [1] },
  //   { title: "Mexico dismantles three synthetic drug labs in Sinaloa", topics: [1] },
  //   { title: "US-Mexico talks: Trump hails deal on migrants to avoid tariffs", topics: [1] },
  //   { title: "Trump supporters start US-Mexico barrier", topics: [1] },
  //   { title: "Trump says 'likely' Mexico tariffs will happen next week", topics: [1] },
  //   { title: "Mexico-US tariffs will harm both countries, warn officials", topics: [1] },
  //   { title: "US-Mexico talks: Trump says more progress needed to avoid tariffs", topics: [1] },
  //   { title: "Migrant children in the US: The bigger picture explained", topics: [1] },
  //   { title: "Mexico 'won't be provoked by US' over migrant row", topics: [1] },
  //   { title: "Trump's threat of Mexico trade war sends markets lower", topics: [1] },
  //   { title: "Trump to hit Mexico with tariffs in anti-immigration measure", topics: [1] },
  //   { title: "Óscar Martínez drowning: El Salvador takes blame", topics: [1] },
  //   { title: "Mexico violence: Ten killed in Michoacán gang shootout", topics: [1] },
  // ],
  // 'Brazil': [
  //   { title: "'Football pitch' of Amazon forest lost every minute", topics: [1] },
  //   // { title: "Neymar gives statement to police in Brazil amid rape allegation", topics: [1] },
  //   // { title: "What's gone wrong with Brazil's economy?", topics: [1] },
  //   // { title: "Brazil economy contracts for the first time since 2016", topics: [1] },
  //   // { title: "Jair Bolsonaro: Man who stabbed Brazil's leader is 'mentally ill'", topics: [1] },
  //   // { title: "Brazil jail violence: Forty inmates found dead at separate prisons", topics: [1] },
  //   // { title: "Majority in Brazil's top court to make homophobia and transphobia crimes", topics: [1] },
  //   { title: "Aliny Godinho stabbing: Mum 'murdered on school run'", topics: [1] },
  //   { title: "Brazil violence: Gunmen kill 11 people in bar in Belém", topics: [1] },
  //   { title: "Brazil's Barão de Cocais waits as dam nearby at risk of collapse", topics: [1] },
  //   { title: "Police seize cocaine ahead of Bolsonaro flight", topics: [1] },
  //   { title: "Brazil's Vale warns another mining dam at risk of collapse", topics: [1] },
  //   { title: "When is the next solar eclipse in my country?", topics: [1] },
  //   { title: "Brazil National Museum: 'Little surprises' salvaged from the ashes", topics: [1] },
  //   { title: "BHP Billiton 'woefully negligent' over Brazil dam collapse", topics: [1] },
  //   { title: "Total solar eclipse 2019: South America awaits sky show", topics: [1] },
  //   { title: "Brazil's President Bolsonaro cancels trip to New York", topics: [1] },
  //   { title: "'Make EU trade with Brazil sustainable'", topics: [1] },
  //   { title: "How Brazil's culture wars are being waged in classrooms", topics: [1] },
  //   { title: "Brazil's Odebrecht corruption scandal explained", topics: [1] },
  //   { title: "Bolsonaro: Brazil must not become 'gay tourism paradise'", topics: [1] },
  //   { title: "EU and Mercosur agree huge trade deal after 20-year talks", topics: [1] },
  // ],
  // 'Pakistan': [
  //   { title: "Uncovering Pakistan's secret human rights abuses", topics: [1] },
  //   { title: "Pakistan general gets life for spying", topics: [1] },
  //   { title: "BA resumes flights to Pakistan after decade-long suspension", topics: [1] },
  //   { title: "Farishta: Outrage over Pakistan child murder", topics: [1] },
  //   { title: "Pakistan vet charged with blasphemy over medicine 'wrapped in religious text'", topics: [1] },
  //   { title: "What are Pakistan's blasphemy laws?", topics: [1] },
  //   { title: "Pakistan attack: Gunmen killed five in Balochistan hotel", topics: [1] },
  //   { title: "Pakistan attack: Gunmen storm five-star hotel in Balochistan", topics: [1] },
  //   { title: "Asia Bibi: Christian leaves Pakistan after blasphemy acquittal", topics: [1] },
  //   { title: "Pakistan to get $6bn IMF lifeline to ease economic crisis", topics: [1] },
  //   { title: "Sam Manekshaw: Why is this Indian war hero trending?", topics: [1] },
  //   { title: "Abdul: 'I can't make any plans for the future'", topics: [1] },
  //   { title: "Pakistan dust storm kills three", topics: [1] },
  //   { title: "Pakistan Data Darbar: Bomber kills nine outside Sufi shrine in Lahore", topics: [1] },
  //   { title: "Plane stowaways: Do any survive?", topics: [1] },
  //   { title: "Pakistan dust storm leaves three people dead", topics: [1] },
  //   { title: "Pakistan Hazara minority protests after bombing in Quetta", topics: [1] },
  //   { title: "Pakistan PM Khan: Kashmir issue 'cannot keep boiling'", topics: [1] },
  // ],
};

